<?php
session_start();

// --- Connect to Database for Live Event List ---
require_once 'config.php'; // Ensures $conn is available

// --- Function to fetch all events (copied from Manage_Team.php) ---
function get_all_events_from_db($conn) {
    $sql = "SELECT e.event_name, s.sport_name, s.category 
            FROM events e 
            JOIN sports s ON e.sport_id = s.sport_id 
            ORDER BY s.sport_name, e.event_name";
    
    $result = $conn->query($sql);
    
    $events = [];
    if ($result) {
        while ($row = $result->fetch_assoc()) {
            $events[] = [
                'sport' => $row['sport_name'],
                'event' => $row['event_name'],
                'category' => $row['category']
            ];
        }
    }
    
    return $events;
}
// --- Fetch the global event list ---
$allEvents = get_all_events_from_db($conn);
$conn->close(); // Close connection


// Load shared teams data from JSON generated by Manage_Team.php
$DATA_DIR = __DIR__ . DIRECTORY_SEPARATOR . 'data';
$TEAMS_JSON = $DATA_DIR . DIRECTORY_SEPARATOR . 'teams.json';
$teams_data = [];
if (file_exists($TEAMS_JSON)) {
    $json = file_get_contents($TEAMS_JSON);
    $data = json_decode($json, true);
    if (is_array($data)) { $teams_data = $data; }
}


// Calculate dynamic statistics
$totalDepartments = count($teams_data);
$totalPoints = $totalDepartments ? array_sum(array_map(function($t){ return (int)($t['points'] ?? 0); }, $teams_data)) : 0;
$pointsThreshold = 200; // Define what constitutes a "top performer"
$topPerformersCount = $totalDepartments ? count(array_filter($teams_data, function($team) use ($pointsThreshold) {
    return ((int)($team['points'] ?? 0)) >= $pointsThreshold;
})) : 0;

// Sort teams by points for the leaderboard
if ($totalDepartments > 0) {
usort($teams_data, function($a, $b) {
        return ((int)($b['points'] ?? 0)) <=> ((int)($a['points'] ?? 0));
});
}

// Current page for nav highlighting
$current_page = basename($_SERVER['PHP_SELF']);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teams Dashboard - PIT Sports Tallying</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" xintegrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
         /* Added from Tournament_Manager_page.php and Event.php for consistency */
         :root {
            --primary-green: #4CAF50;
            --primary-dark: #2E7D32;
            --accent-gold: #FFD700;
            --accent-silver: #C0C0C0;
            --accent-bronze: #CD7F32;
            --bg-light: #F8F9FA;
            --bg-white: #FFFFFF;
            --text-dark: #1A1A1A;
            --text-muted: #6C757D;
            --shadow-sm: 0 2px 8px rgba(0,0,0,0.06);
            --shadow-md: 0 4px 16px rgba(0,0,0,0.08);
            --shadow-lg: 0 8px 32px rgba(0,0,0,0.12);
            --transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }

        body {
            background: linear-gradient(to bottom,rgba(245, 16, 16, 0.32));
            margin: 0;
            padding: 0;
            min-height: 100vh;
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; /* Updated font */
            display: flex;
            flex-direction: column;
        }

         /* Navbar Enhancement - Consistent across pages */
        .navbar {
            background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%) !important;
            box-shadow: 0 4px 20px rgba(0,0,0,0.15);
            padding: 1rem 0;
            backdrop-filter: blur(10px);
        }

        .navbar-brand {
            transition: var(--transition);
        }

        .navbar-brand:hover {
            transform: translateY(-2px);
        }

        .brand-logo {
            filter: drop-shadow(0 2px 4px rgba(255,255,255,0.1));
        }

        .brand-heading {
            font-family: 'Poppins', sans-serif;
            font-weight: 700;
            letter-spacing: -0.5px;
        }

        .nav-link {
            font-weight: 500;
            font-size: 0.95rem;
            padding: 0.5rem 1.25rem !important;
            margin: 0 0.25rem;
            border-radius: 8px;
            transition: var(--transition);
            position: relative;
        }

        .nav-link::after {
            content: '';
            position: absolute;
            bottom: 0;
            left: 50%;
            width: 0;
            height: 2px;
            background: var(--primary-green);
            transition: var(--transition);
            transform: translateX(-50%);
        }

        .nav-link:hover::after,
        .nav-link.active::after {
            width: 80%;
        }

        .nav-link:hover {
            background: rgba(255,255,255,0.1);
            color: var(--primary-green) !important;
        }
        
        .btn-danger, .btn-success {
            padding: 0.6rem 1.5rem;
            border-radius: 10px;
            font-weight: 600;
            transition: var(--transition);
            border: none;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }

        .btn-danger:hover, .btn-success:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(0,0,0,0.2);
        }
        /* End Navbar Enhancement */
        
        /* === Hero Section (Consistent with Event.php) === */
        .hero-section {
            background: linear-gradient(135deg, rgba(255,255,255,0.9) 0%, rgba(233,236,239,0.9) 100%);
            border-radius: 16px;
            padding: 32px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }

        .stat-card-new {
            background: white;
            border-radius: 12px;
            padding: 20px 15px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.06);
            transition: transform 0.2s, box-shadow 0.2s;
            height: 100%; /* Ensure uniform height in the row */
        }

        .stat-card-new:hover {
            transform: translateY(-4px);
            box-shadow: 0 6px 16px rgba(0,0,0,0.12);
        }

        /* NEW: Teams Roster Container Style (similar to Hero, but slightly simpler) */
        .roster-container {
            background: #fff;
            border-radius: 16px;
            padding: 32px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }
        
        /* === Department Card Styling (Enhanced for Hover Animation) === */
        .department-card {
            background-color: #f8f9fa; 
            border-radius: 12px;
            box-shadow: var(--shadow-sm);
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            height: 100%; 
            padding: 24px;
            position: relative; /* Essential for ::before pseudo-element */
            overflow: hidden; /* Ensures inner elements stay contained */
            border-left: 0; /* Remove original border-left style */
        }

        /* Accent Bar (New: using ::before) */
        .department-card::before {
            content: '';
            position: absolute;
            left: 0;
            top: 0;
            bottom: 0;
            /* Use the inline style border-left-color set by PHP */
            background-color: inherit; 
            width: 6px; 
            transition: var(--transition);
            /* Start invisible and flat */
            transform: translateX(0); 
            opacity: 0;
        }
        
        /* Hover Effect: Slide and Lift */
        .department-card:hover {
            transform: translateX(8px); /* Slide effect */
            box-shadow: var(--shadow-lg); /* Lift effect */
            background-color: #fff; /* White background on hover */
        }

        /* Hover Effect: Accent Bar Appears */
        .department-card:hover::before {
             /* IMPORTANT: We cannot directly read the inline style (border-left-color) 
                from PHP into the pseudo-element's background-color *in this block*. 
                We use JS below to set the accent color on hover, but for pure CSS, 
                we'll temporarily rely on the PHP's inline style as a fallback */
            opacity: 1;
            /* Since we removed the border-left and use ::before, we must now use 
               a CSS trick or JS to get the color. For clean CSS, we'll use a 
               data-attribute in JS, but for now, we'll rely on the JS below. */
        }

        .department-logo {
            width: 100px;
            height: 100px;
            margin: 0 auto 10px;
            display: block;
            object-fit: cover;
            border-radius: 50%;
            padding: 5px;
            background: #e9ecef;
            border: 3px solid #e9ecef; /* Initial logo border color */
            transition: var(--transition);
        }
        
        /* Hover Effect: Logo Border Change */
        .department-card:hover .department-logo {
            transform: scale(1.1) rotate(2deg);
            border-color: var(--primary-green); /* Green border on hover */
        }

        .department-badge {
            font-size: 0.75rem;
            font-weight: bold;
            padding: 4px 10px;
            border-radius: 50rem;
            display: inline-block;
            margin-bottom: 8px;
            background-color: #e9ecef;
            color: #495057;
        }
        .department-name {
            font-weight: 700;
            font-size: 1.35rem;
            color: #2c3e50;
        }
        .truncate-text {
            display: -webkit-box;
            -webkit-line-clamp: 3;
            -webkit-box-orient: vertical;
            overflow: hidden;
            text-overflow: ellipsis;
            line-height: 1.5;
            min-height: 4.5em;
        }
        
        .btn-full-width {
            width: 100%;
        }

        /* === Modal Styling (Refinement) === */
        .details-card {
            border-radius: 12px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
            background-color: #fff;
            padding: 20px;
            
        }
        .details-title {
            font-weight: 600;
            font-size: 1.1rem;
            color: #2c3e50;
            margin-bottom: 15px;
            border-bottom: 1px dashed #e9ecef;
            padding-bottom: 8px;
        }
        .dean-avatar {
            width: 60px; /* Slightly smaller dean avatar */
            height: 60px;
            border-radius: 50%;
            object-fit: cover;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .list-group-item {
            border: none;
            padding: 0.5rem 0;
            background-color: transparent;
        }
        .modal-body .display-4, .modal-body .display-3 {
            line-height: 1;
            margin: 0.2em 0;
        }
        /* rotate chevrons when open (kept original JS style) */
        .details-card .rotated { transform: rotate(180deg); transition: transform .18s ease; display:inline-block; }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid d-flex align-items-center justify-content-between">
        <a class="navbar-brand d-flex align-items-center interactive-brand" href="Tournament_Manager_page.php" style="cursor: pointer;">
            <img src="imageslogo.png" alt="Logo" class="me-2 brand-logo" style="height: 50px; width: 48px; object-fit: contain; transition: filter 0.2s;">
            <div class="d-flex flex-column lh-sm">
                <strong class="text-white brand-heading" style="font-size: 1.25rem; transition: color 0.2s;">PIT SPORTS TALLYING</strong>
                <small class="text-light brand-subheading" style="font-size: 0.75rem; transition: color 0.2s;">Official College Tournament System</small>
            </div>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto align-items-center">
                <li class="nav-item">
                    <a class="nav-link <?= ($current_page == 'Tournament_Manager_page.php') ? 'active' : '' ?>" href="Tournament_Manager_page.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= ($current_page == 'Event.php') ? 'active' : '' ?>" href="Event.php">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= ($current_page == 'Teams.php') ? 'active' : '' ?>" href="Teams.php">Teams</a>
                </li>
                <li class="nav-item">
                    <?php if (isset($_SESSION['email'])): ?>
                        <a href="logout.php" class="btn btn-danger ms-3">Logout</a>
                    <?php else: ?>
                        <a href="login.php" class="btn btn-success ms-3">Admin Login</a>
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container" style="padding-top: 100px; padding-bottom: 40px;">
    
    <div class="hero-section mb-5">
        <div class="row align-items-center">
            <div class="col-lg-6 mb-4 mb-lg-0">
                <h1 class="display-4 fw-bold mb-3 text-dark">
                    <img src="images/DepartmentIcon.png" alt="Departments Icon" class="me-2" style="width: 3.5rem; height: 3.5rem; object-fit: contain;">
                    Participating Teams
                </h1>
                <p class="lead text-muted">A comprehensive look at all departments competing in the tournament.</p>
            </div>
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-4">
                        <div class="stat-card-new text-center">
                            <img src="images/DepartmentIcon.png" alt="Departments Icon" style="width: 2.5em; height: 2.5em;">
                            <div class="fw-bold fs-3 mt-2 text-primary"><?= $totalDepartments ?></div>
                            <div class="text-muted small">Total Departments</div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="stat-card-new text-center">
                            <img src="images/TopperformanceIcon.png" alt="Top performance Icon" style="width: 2.5em; height: 2.5em;">
                            <div class="fw-bold fs-3 mt-2 text-success"><?= $topPerformersCount ?></div>
                            <div class="text-muted small">Top Performers</div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="stat-card-new text-center">
                            <img src="images/PointsIcon.png" alt="Total Points Icon" style="width: 2.5em; height: 2.5em;">
                            <div class="fw-bold fs-3 mt-2 text-warning"><?= $totalPoints ?></div>
                            <div class="text-muted small">Total Medals Earned</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="roster-container">
        <h2 class="fw-bold mb-4 text-dark">
            <i class="fas fa-list-alt me-2 text-primary"></i> College Roster
        </h2>
        
        <div class="row g-4 w-100 justify-content-center">
            <?php if (count($teams_data) === 0): ?>
                <div class="col-12">
                    <div class="alert alert-info text-center">No Teams Available</div>
                </div>
            <?php else: ?>
            <?php foreach ($teams_data as $team): ?>
            <div class="col-12 col-md-6 col-lg-4 d-flex">
                <?php 
                    // Extract accent color for use in JS and the new CSS
                    $accentColor = htmlspecialchars($team['accentColor'] ?? '#2c3e50', ENT_QUOTES);
                ?>
                <div class="department-card d-flex flex-column w-100" style="border-color: <?= $accentColor ?>;" data-accent-color="<?= $accentColor ?>">
                    <img src="<?= htmlspecialchars($team['logo'] ?? '', ENT_QUOTES) ?>" alt="<?= htmlspecialchars($team['badge'] ?? '', ENT_QUOTES) ?>" class="department-logo team-logo-img" data-team-badge="<?= htmlspecialchars($team['badge'] ?? '', ENT_QUOTES) ?>">
                    <div class="text-center">
                            <span class="department-badge"><?= htmlspecialchars($team['badge'] ?? '', ENT_QUOTES) ?></span>
                            <h5 class="department-name mb-1"><?= htmlspecialchars($team['name'] ?? '', ENT_QUOTES) ?></h5>
                        <p class="text-muted small truncate-text">
                                <?= htmlspecialchars($team['description'] ?? '', ENT_QUOTES) ?>
                        </p>
                    </div>
                    <div class="mt-auto d-grid gap-2">
                            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#detailsModal" data-team-badge="<?= htmlspecialchars($team['badge'] ?? '', ENT_QUOTES) ?>">
                                <i class="fas fa-info-circle me-1"></i> Full Details
                            </button>
                            <a href="?view=leaderboard" class="btn btn-outline-secondary btn-full-width">
                            <i class="fas fa-chart-bar me-1"></i> View Leaderboard
                        </a>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>
        </div>
    </div>

<div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                </div>
            <div class="modal-body">
                </div>
        </div>
    </div>
</div>


    <footer class="bg-dark text-white py-3 mt-auto w-100">
        <div class="container text-center">
            <small>&copy; <?php echo date("Y"); ?> PIT SPORTS TALLYING. All rights reserved.</small><br>
            <small>Developed by Tsunayoshi Sawada</small>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" xintegrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eOzr0/pGFN9i1S" crossorigin="anonymous"></script>

    <script>
document.addEventListener('DOMContentLoaded', function() {
  const detailsModal = document.getElementById('detailsModal');
  const teamsData = <?= json_encode($teams_data); ?>;
  const allEventsData = <?= json_encode($allEvents); ?>; // <-- DATA FROM PHP
  
  // --- JS to handle the dynamic accent bar color on hover ---
  document.querySelectorAll('.department-card').forEach(card => {
    const accentColor = card.getAttribute('data-accent-color');
    
    if (accentColor) {
        // Set the CSS Custom Property on the card for the ::before pseudo-element to use
        card.style.setProperty('--accent-slide-color', accentColor);

        // We use mouseenter/mouseleave to dynamically update the pseudo-element's color 
        // by applying the color directly to the ::before pseudo-element via a CSS rule.
        // Since direct manipulation isn't possible, we'll use a CSS variable trick 
        // combined with the hover state to read the color.
        
        // CSS Trick: Set the ::before color using the variable on hover
        card.addEventListener('mouseenter', () => {
            // This is the cleanest way to pass the inline PHP color to the pseudo-element
            // which should now be reading the '--accent-slide-color' CSS variable.
            // Since we use the attribute/style in PHP, we just ensure the CSS is set up right.
            card.style.setProperty('--accent-slide-color', accentColor);
        });
        // Note: No mouseleave needed as CSS handles the exit gracefully.
    }
  });
    
  // --- Re-applying the CSS logic to correctly use the accent color ---
  // We need to inject a tiny bit of CSS that forces the pseudo-element to use 
  // the custom property on hover. (This is generally done in the main CSS block, 
  // but since we are modifying, I'll provide the final structure).
  const styleSheet = document.createElement("style");
  styleSheet.type = "text/css";
  styleSheet.innerText = `
    .department-card::before {
        background-color: var(--accent-slide-color);
    }
  `;
  document.head.appendChild(styleSheet);
  
  // Original border-left style should be removed, which was done in the PHP code now:
  // .department-card { border-left: 0; } 
  // This ensures the full width accent bar is handled only by ::before

  
  // --- Original Modal Logic (Kept Intact) ---

  if (!detailsModal) {
    console.warn('detailsModal not found.');
    return;
  }

  detailsModal.addEventListener('show.bs.modal', function(event) {
    const button = event.relatedTarget;
    if (!button) return;

    const teamBadge = button.getAttribute('data-team-badge');
    const team = teamsData.find(t => t && t.badge === teamBadge);
    const modalHeader = detailsModal.querySelector('.modal-header');
    const modalBody = detailsModal.querySelector('.modal-body');

    if (!team) {
      if (modalBody) modalBody.innerHTML = '<div class="p-3">Team data not found.</div>';
      return;
    }

    // unique key to guarantee unique ids per modal open
    const uniqueKey = (team.badge || 'team').toString().replace(/[^A-Za-z0-9_-]/g, '_') + '_' + Math.random().toString(36).substr(2,6);

    // --- Build sports lists (Now uses the global allEventsData) ---
    const sportsEvents = Array.isArray(allEventsData) ? allEventsData : [];
    
    // Show 5 events, hide the rest
    const sportsVisibleLimit = 3; 
    
    // Create HTML for visible events
    const sportsVisible = sportsEvents.slice(0, sportsVisibleLimit).map(evt => `
      <li class="list-group-item d-flex justify-content-between align-items-center p-2">
        <span><i class="fas fa-futbol text-primary me-2"></i><strong>${evt.sport || ''}:</strong> ${evt.event || ''}</span>
        <span class="badge bg-secondary">${evt.category || 'N/A'}</span>
      </li>`).join('');
      
    // Create HTML for hidden events
    const sportsHidden = sportsEvents.slice(sportsVisibleLimit).map(evt => `
      <li class="list-group-item d-flex justify-content-between align-items-center p-2">
        <span><i class="fas fa-futbol text-primary me-2"></i><strong>${evt.sport || ''}:</strong> ${evt.event || ''}</span>
        <span class="badge bg-secondary">${evt.category || 'N/A'}</span>
      </li>`).join('');

    const sportsId = `collapseSports-${uniqueKey}`;
    const sportsAccordionId = `accordionSports-${uniqueKey}`;

    // --- Build matches lists ---
    const matches = Array.isArray(team.upcoming_matches) ? team.upcoming_matches : [];
    const matchesVisible = matches.slice(0,3).map(m => `
      <tr>
        <td class="fw-bold">${m.opponent}</td>
        <td>${m.date}</td>
        <td>${m.venue}</td>
      </tr>`).join('');
    const matchesHidden = matches.slice(3).map(m => `
      <tr>
        <td class="fw-bold">${m.opponent}</td>
        <td>${m.date}</td>
        <td>${m.venue}</td>
      </tr>`).join('');

    const matchesId = `collapseMatches-${uniqueKey}`;
    const matchesAccordionId = `accordionMatches-${uniqueKey}`;

    // header
    modalHeader.innerHTML = `
      <div class="d-flex align-items-center w-100">
        <div class="d-flex align-items-center gap-3">
          <img src="${team.logo || 'https://placehold.co/80x80/6c757d/ffffff?text=Logo'}" alt="${team.badge} Logo" style="width:80px;height:80px;" class="rounded-circle shadow-sm">
          <div>
            <h5 class="modal-title fw-bold mb-0" id="detailsModalLabel">${team.name || ''}</h5>
            <p class="text-muted fw-bold mb-0">${team.badge || ''}</p>
          </div>
        </div>
        <button type="button" class="btn-close ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    `;

    // sportsSection wrapped in its own accordion
    const sportsSection = `
      <div class="accordion" id="${sportsAccordionId}">
        <div class="accordion-item border-0 p-0">
          <div class="d-flex justify-content-between align-items-center mb-2">
            <h5 class="details-title mb-0"><i class="fas fa-list-alt me-2 text-primary"></i>All Available Events</h5>
            ${sportsHidden ? `
              <button class="btn btn-link p-0 border-0 bg-transparent shadow-none sports-toggle" 
                      type="button" data-bs-toggle="collapse" data-bs-target="#${sportsId}" 
                      aria-expanded="false" aria-controls="${sportsId}" data-bs-parent="#${sportsAccordionId}">
                <i class="fas fa-chevron-down"></i>
              </button>
            ` : ''}
          </div>

          <ul class="list-group list-group-flush">${sportsVisible}</ul>

          ${sportsHidden ? `
            <div id="${sportsId}" class="collapse mt-2" data-bs-parent="#${sportsAccordionId}">
              <ul class="list-group list-group-flush">${sportsHidden}</ul>
            </div>
          ` : ''}
        </div>
      </div>
    `;

    // matchesSection wrapped in its own accordion
    const matchesSection = `
      <div class="accordion" id="${matchesAccordionId}">
        <div class="accordion-item border-0 p-0">
          <div class="d-flex justify-content-between align-items-center mb-2">
            <h5 class="details-title mb-0"><i class="fas fa-calendar-check me-2 text-info"></i>Upcoming Matches</h5>
            ${matchesHidden ? `
              <button class="btn btn-link p-0 border-0 bg-transparent shadow-none matches-toggle" 
                      type="button" data-bs-toggle="collapse" data-bs-target="#${matchesId}" 
                      aria-expanded="false" aria-controls="${matchesId}" data-bs-parent="#${matchesAccordionId}">
                <i class="fas fa-chevron-down"></i>
              </button>
            ` : ''}
          </div>

          <div class="table-responsive">
            <table class="table table-sm table-borderless mb-0">
              <thead>
                <tr>
                  <th class="text-muted">Opponent</th>
                  <th class="text-muted">Date</th>
                  <th class="text-muted">Venue</th>
                </tr>
              </thead>
              <tbody>${matchesVisible}</tbody>
            </table>
          </div>

          ${matchesHidden ? `
            <div id="${matchesId}" class="collapse mt-2" data-bs-parent="#${matchesAccordionId}">
              <table class="table table-sm table-borderless mb-0">
                <tbody>${matchesHidden}</tbody>
              </table>
            </div>
          ` : ''}
        </div>
      </div>
    `;

    // assemble modal body (keeps your 2-column grid)
    modalBody.innerHTML = `
      <div class="row row-cols-1 row-cols-md-2 g-4 w-100">
        <div class="col">
          <div class="details-card">
            <h5 class="details-title"><i class="fas fa-graduation-cap me-2 text-info"></i>Dean</h5>
            <div class="d-flex align-items-center gap-3">
              <img id="deanPhotoImg" src="https://placehold.co/80x80/6c757d/ffffff?text=Dean" alt="Dean's Photo" class="dean-avatar">
              <span class="fw-bold">${team.dean_name || ''}</span>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="details-card text-center">
            <h5 class="details-title"><i class="fas fa-users me-2 text-success"></i>Total Students</h5>
            <h2 class="display-4 fw-bold text-primary my-auto">${team.total_students || 0}</h2>
          </div>
        </div>

        <div class="col">
          <div class="details-card">${sportsSection}</div>
        </div>

        <div class="col">
          <div class="details-card">${matchesSection}</div>
        </div>

        <div class="col">
          <div class="details-card text-center">
            <h5 class="details-title"><i class="fas fa-trophy me-2 text-warning"></i>Total Medals</h5>
            <div class="d-flex justify-content-center align-items-center gap-4 my-3">
              <div class="text-center"><span class="medal-badge" style="color: gold;">🥇</span><br><span class="fw-bold fs-4">${(team.medals && team.medals.gold) || 0}</span></div>
              <div class="text-center"><span class="medal-badge" style="color: silver;">🥈</span><br><span class="fw-bold fs-4">${(team.medals && team.medals.silver) || 0}</span></div>
              <div class="text-center"><span class="medal-badge" style="color: #cd7f32;">🥉</span><br><span class="fw-bold fs-4">${(team.medals && team.medals.bronze) || 0}</span></div>
            </div>
            <hr>
            <h6 class="text-muted">Total: <span class="fw-bold text-dark fs-5">${((team.medals && team.medals.gold) || 0) + ((team.medals && team.medals.silver) || 0) + ((team.medals && team.medals.bronze) || 0)}</span></h6>
          </div>
        </div>

        <div class="col">
          <div class="details-card text-center">
            <h5 class="details-title"><i class="fas fa-star me-2 text-danger"></i>Total Points</h5>
            <h1 class="display-3 fw-bolder text-danger">${team.points || 0}</h1>
          </div>
        </div>
      </div>
    `;

    // rotate chevrons when their collapse toggles
    try {
      const sportsBtn = modalBody.querySelector(`[data-bs-target="#${sportsId}"]`);
      const matchesBtn = modalBody.querySelector(`[data-bs-target="#${matchesId}"]`);
      const sportsCollapse = modalBody.querySelector(`#${sportsId}`);
      const matchesCollapse = modalBody.querySelector(`#${matchesId}`);

      function attachRotate(btn, collapseEl) {
        if (!btn || !collapseEl) return;
        const icon = btn.querySelector('i');
        collapseEl.addEventListener('shown.bs.collapse', () => { if (icon) icon.classList.add('rotated'); });
        collapseEl.addEventListener('hidden.bs.collapse', () => { if (icon) icon.classList.remove('rotated'); });
      }
      attachRotate(sportsBtn, sportsCollapse);
      attachRotate(matchesBtn, matchesCollapse);
    } catch (e) {
      // ignore rotation errors
    }

    // Resolve dean photo (same logic you had)
    (function(){
      const imgEl = modalBody.querySelector('#deanPhotoImg');
      if (!imgEl) return;
      const safe = (team.badge || '').replace(/[^A-Za-z0-9_-]/g,'_');
      const base = 'uploads/deans/' + safe;
      const candidates = ['.jpg','.jpeg','.png','.gif','.webp'];
      let idx = 0;
      function tryNext() {
        if (idx >= candidates.length) return;
        const testUrl = base + candidates[idx] + '?v=' + Date.now();
        const tester = new Image();
        tester.onload = function(){ imgEl.src = testUrl; };
        tester.onerror = function(){ idx++; tryNext(); };
        tester.src = testUrl;
      }
      tryNext();
      const intervalId = setInterval(tryNext, 4000);
      detailsModal.addEventListener('hidden.bs.modal', function(){ clearInterval(intervalId); }, { once: true });
    })();
  });
});
</script>

</body>
</html>